# Generated by Django 5.2.7 on 2025-12-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisionGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_graph_id', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=512)),
                ('date_created', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
