# Generated by Django 5.2.7 on 2025-12-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moba_ai_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiongraph',
            name='vision_graph_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
